config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :train_details do
    resources :reservations
  end

  get 'search', to: 'train_details#search'
  get 'reservations/reservation_details'

  root 'reservations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  before_create :generate_pnr  
  belongs_to :train_detail
  belongs_to :user
 
  validates :traveller, presence: true



  def generate_pnr
    self.pnr = rand(1000000000..999999999)
  end

 
end

app/models/train_detail.rb
class TrainDetail < ApplicationRecord
   
    has_many :users, through: :reservation
    has_many :reservations

    validates :name, presence: true
    validates :source, presence: true
    validates :destination, presence: true
    validates :train_no, presence: true, length: { maximum: 5 },numericality: true
    validates :frequency, presence: true
    validates :distance, presence: true
    validates :fare, presence: true, numericality: true
    validates :frequency, presence: true
    validates :departure_time, presence: true
    validates :arrival_time, presence: true

    enum :frequency,["weekly","daily"]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :train_details , through: :reservation
  has_many :reservations

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :age, presence: true
  validates :gender, presence: true
  validates :Phone, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :age,:gender, :Phone, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :age, :gender, :Phone, :email, :password, :current_password)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  def index
    @reservations = Reservation.all
  end

  def show
  end

  
  def new
    @reservation = Reservation.new
    @train_detail = TrainDetail.all
    @train_detail = TrainDetail.find(params[:train_detail_id])
  end
  
  def reservation_details
    @reservations = current_user.reservations
  end
  
  def edit
    @reservation = Reservation.find(params[:id])
  end

  def create
    @train_detail = TrainDetail.find(params[:train_detail_id])
    @reservation = @train_detail.reservations.new(reservation_params)
    @reservation.user = current_user

    @reservation.amount = @reservation.traveller * @train_detail.fare  

    if @reservation.save


      EticketMailer.with(user:current_user,reservation:@reservation).shipping_confirmation_email.deliver_now
      redirect_to reservations_reservation_details_path	, notice: "Your reservation has been created successfully."
    else
      render :new
    end
  

  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
  
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
   
    @reservation.destroy
    redirect_to train_detail_reservations_path
  end

  private
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit!   
    end
end

app/controllers/train_details_controller.rb
class TrainDetailsController < ApplicationController


  def index
    @train_details = TrainDetail.all
  end

  def show
    @train_detail = TrainDetail.find(params[:id])
  end

  
  def new
    @train_detail = TrainDetail.new
  end

  
  def edit
    @train_detail = TrainDetail.find(params[:id])
  end

  
  def create
    @train_detail = TrainDetail.new(train_detail_params)
      
    if @train_detail.save 
        
        redirect_to train_details_path
      
      else 
        render :new, status: :unprocessable_entity 
      end
    
  
  
      
  end


  def update
    @train_detail = TrainDetail.find(params[:id])

    if @train_detail.update(train_detail_params)
      redirect_to train_details_path
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @train_detail = TrainDetail.find(params[:id])
   
    @train_detail.destroy
    redirect_to train_details_path(@train_detail)

  end

  def search
    @source = params[:source]
    @destination = params[:destination]
    @departure_time = params[:departure_time]
    @results = TrainDetail.where("source LIKE ? AND destination LIKE ? AND departure_time LIKE ?","%#{@source}%", "%#{@destination}%", "%#{@departure_time}%")
  end

  private
    def train_detail_params
     
      params.require(:train_detail).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/train_details_helper.rb
module TrainDetailsHelper
end

app/views/home/index.html.erb
<h1>Home index</h1>

<%= link_to "Logout",destroy_user_session_path, data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
  <link rel ="stylesheet" href="assets/stylesheets/rail.css">

    <title>ETicket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

  <div class= 'container'>
  <% unless current_page?(new_user_session_path)%>
  <%= render 'shared/header'%>
<%end%>
    <%= yield %>
    </div>
  <div>
<%= render 'shared/footer'%>
</div>
    </body>
    
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>">
</div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show this reservation", @reservation %> |
  <%= link_to "Back to reservations", reservations_path %>
</div>

app/views/reservations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reservations</h1>

<div id="reservations">
  <% @reservations.each do |reservation| %>
    <%= render reservation %>
    <p>
    </p>
  <% end %>
</div>

<%= form_tag search_path, method: :get do %>
  <div>
  <%=label_tag :source, "Source:"%><br>
  <%=text_field_tag :source, params[:source]%>
  </div>
  
  <div>
  <%=label_tag :destination, "Destination:"%><br>
  <%=text_field_tag :destination, params[:destination]%>
  </div>

  <div>
  <%=label_tag :departure_time, "Date:"%><br>
  <%=date_field_tag :departure_time, params[:departure_time]%>
  </div>
  <br>
  <div>
  <%= submit_tag "Search" %>
  </div>
  <%end%>
  <br>

<%= link_to "Logout",destroy_user_session_path, data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= form_for @reservation, url: train_detail_reservations_path(@train_detail) do |f| %>
  
  <%= f.date_field :journey_date,value: @train_detail.departure_time, type: "hidden" %>
  
  <%= f.label :traveller %>
  <%= f.text_field :traveller, class: "form-control" %>

 
  
  <%= f.text_field :amount,value: 0, type: "hidden" %>
  
  <%= f.submit "Book Ticket", class: "btn btn-primary" %>
  <% end %>

<div>

</div>

app/views/reservations/reservation_details.html.erb
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  opacity:15;
}
th, td {
  padding: 5px;
  text-align: left;
}
</style>

<h1>Reservation Details</h1>
<table style="width:100%; background-color:white">

  <thead>
    <tr>
    <th>Source</th>
      <th>Destination</th>
      <th>Train Name</th>

      <th>Train No.</th>
      <th>Booking Date</th>
      <th>PNR</th>
      <th>Journey Date</th>
      <th>Travellers</th>
      <th> Fare (INR) </th>
      <th> Action </th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>

      <tr>
      <td><%= reservation.train_detail.source %></td>
      <td><%= reservation.train_detail.destination %></td>
      <td><%= reservation.train_detail.name %></td>
      <td><%= reservation.train_detail.train_no %></td>
        <td><%= reservation.booking_date %></td>
        <td><%= reservation.pnr %></td>
        <td><%= reservation.journey_date %></td>
        <td><%= reservation.traveller %></td>
        <td><%= reservation.amount %></td>

        <td><li><%= link_to "Cancel Booking", train_detail_reservation_path(reservation.train_detail,reservation), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %></li></td>
      </tr>
    <% end %>
  </tbody>
</table>


<center><b style="background-color:white"> आपकी यात्रा मंगलमय हो! </b></center>

app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

<div>


  
  <%= link_to "Edit this reservation", edit_reservation_path(@reservation) %> |
  <%= link_to "Back to reservations", reservations_path %>

  <%= button_to "Destroy this reservation", @reservation, method: :delete %>
</div>

app/views/shared/_footer.html.erb
<! DOCTYPE html>  
<html lang="en">  
<head>  
  <title> Bootstrap 4 Footer with Social icons </title>  
  <meta charset="utf-8">  
  <meta name="viewport" content="width=device-width, initial-scale=1">  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"> </script>  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"> </script>  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"> </script>  
   <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >  
</head>  
<style>  
h2 {  
padding: 25px 0;  
text-align: center;  
color: #fff;  
background: #7c8490;  
}  
footer {  
 background: #4c5054;  
  color: white;  
  margin-top:100px;  
}  
footer a {  
  color: #fff;  
  font-size: 14px;  
  transition-duration: 0.2s;  
}  
footer a:hover {  
  color: #FA944B;  
  text-decoration: none;  
}  
.copy {  
  font-size: 12px;  
  padding: 10px;  
  border-top: 1px solid #FFFFFF;  
}  
.footer-middle {  
  padding-top: 2em;  
  color: white;  
}  
ul.social-network {  
  list-style: none;  
  display: inline;  
  margin-left: 0 !important;  
  padding: 0;  
}  
ul.social-network li {  
  display: inline;  
  margin: 0 5px;  
}  
  
.social-network a.icoFacebook:hover {  
  background-color: #3B5998;  
}  
.social-network a.icoLinkedin:hover {  
  background-color: #007bb7;  
}  
.social-network a.icoFacebook:hover i  
{  
  color: #fff;  
}  
.social-network a.icoLinkedin:hover i {  
  color: #fff;  
}  
.social-network a.socialIcon:hover {  
  color: #44BCDD;  
}  
.socialHoverClass {  
  color: #44BCDD;  
}  
.social-circle li a {  
  display: inline-block;  
  position: relative;  
  margin: 0 auto 0 auto;  
  -moz-border-radius: 50%;  
  -webkit-border-radius: 50%;  
  border-radius: 50%;  
  text-align: center;  
  width: 30px;  
  height: 30px;  
  font-size: 15px;  
}  
.social-circle li i {  
  margin: 0;  
  line-height: 30px;  
  text-align: center;  
}  
.social-circle li a:hover i  
{  
  -moz-transform: rotate(360deg);  
  -webkit-transform: rotate(360deg);  
  -ms--transform: rotate(360deg);  
  transform: rotate(360deg);  
  -webkit-transition: all 0.2s;  
  -moz-transition: all 0.2s;  
  -o-transition: all 0.2s;  
  -ms-transition: all 0.2s;  
  transition: all 0.2s;  
}  
.triggeredHover {  
  -moz-transform: rotate(360deg);  
  -webkit-transform: rotate(360deg);  
  -ms--transform: rotate(360deg);  
  transform: rotate(360deg);  
  -webkit-transition: all 0.2s;  
  -moz-transition: all 0.2s;  
  -o-transition: all 0.2s;  
  -ms-transition: all 0.2s;  
  transition: all 0.2s;  
}  
.social-circle i {  
  color: #595959;  
  -webkit-transition: all 0.8s;  
  -moz-transition: all 0.8s;  
  -o-transition: all 0.8s;  
  -ms-transition: all 0.8s;  
  transition: all 0.8s;  
}  
.social-network a {  
  background-color: #F9F9F9;  
}  
..social-network a:hover {  
background: #ff304d;  
}  
</style>  
<body>  
  
<footer class="mainfooter" role="contentinfo">  
  <div class="footer-middle">  
  <div class="container">  
    <div class="row">  
      <div class="col-md-3 col-sm-6">  
        <div class="footer-pad">  
          <h4> </h4>  
          <ul class="list-unstyled">  
            <li> <a href="#"> </a> </li>  
            <li> <a href="#">Payment Center</a></li>  
            <li> <a href="#"> Contact Directory </a></li>  
            <li> <a href="#">Forms</a></li>  
            <li> <a href="#">News and Updates</a></li>  
            <li> <a href="#">FAQs</a></li>  
          </ul>  
        </div>  
      </div>  
      <div class="col-md-3 col-sm-6">  
        <div class="footer-pad">  
          
          <ul class="list-unstyled">  
            <li><a href="#"> Blog </a> </li>  
            <li><a href="#">Accessibility</a> </li>  
            <li><a href="#">Disclaimer</a></li>  
            <li><a href="#">Privacy Policy</a></li>  
            <li><a href="#">FAQs</a></li>  
            <li><a href="#">Webmaster</a></li>  
          </ul>  
        </div>  
      </div>  
      <div class="col-md-3 col-sm-6">  
        <div class="footer-pad">  
        
          <ul class="list-unstyled">  
            <li> <a href="#"> Parks and Recreation </a> </li>  
            <li> <a href="#"> Public Works </a> </li>  
            <li> <a href="#">Police Department</a> </li>  
            <li> <a href="#"> Fire </a> </li>  
            <li> <a href="#"> Rights and Regulations </a> </li>  
          </ul>  
        </div>  
      </div>  
        <div class="col-md-3">  
        
            <ul class="social-network social-circle">  
             <li> <a href="#" class="icoFacebook" title="Facebook"> <i class="fa fa-facebook"> </i> </a> </li>  
             <li> <a href="#" class="icoLinkedin" title="Linkedin"> <i class="fa fa-linkedin"> </i> </a> </li>  
    <li> <a href="#"> <i class="fa fa-youtube" aria-hidden="true"> </i> </a> </li>  
            </ul>               
    </div>  
    </div>  
    <div class="row">  
    <div class="col-md-12 copy">  
    <p class="text-center"> © Copyright 2023 - E-Ticket.  All rights reserved. </p>  
    </div>  
    </div>  
  </div>  
  </div>  
</footer>  
  </body>  
</html>  

app/views/shared/_header.html.erb
<h1> Welcome To E-Ticket</h1>
<nav class="navbar navbar-expand-lg navbar-light bg-light">



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
      <a class="nav-link" <%=link_to "My Reservations", reservations_reservation_details_path %></a>
      </li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>


      <li class="nav-item">
      <a class="nav-link" <%=link_to "Log Out", destroy_user_session_path, data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %></a>
      </li>

    
   
  </div>
</nav>

app/views/train_details/_form.html.erb
<%= form_with(model: train_detail) do |form| %>
  <% if train_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(train_detail.errors.count, "error") %> prohibited this train_detail from being saved:</h2>

      <ul>
        <% train_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/train_details/_train_detail.html.erb
<div id="<%= dom_id train_detail %>">
</div>

app/views/train_details/edit.html.erb
<h1>Editing train detail</h1>

<%= render "form", train_detail: @train_detail %>

<br>
<h1>New train detail</h1>

<h2>Sign up</h2>
<%= form_with model: @train_detail do |f| %>



  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :train_no %><br />
    <%= f.text_field :train_no %>
  </div>

  <div class="field">
  <%= f.label :departure_time %><br />
  <%= f.datetime_field :departure_time %>
  </div>


  <div class="field">
  <%= f.label :arrival_time %><br />
  <%= f.datetime_field :arrival_time %>
  </div>

  <div class="field">
  <%= f.label :source %><br />
  <%= f.text_field :source %>
  </div>

  <div class="field">
  <%= f.label :destination %><br />
  <%= f.text_field :destination %>
  </div>

<%= f.select :frequency, options_for_select(TrainDetail.frequencies.map{|k,v| [k.humanize.capitalize,k]}) %>
  <div class="field">
  <%= f.label :distance %><br />
  <%= f.text_field :distance %>
  </div>


  <div class="field">
  <%= f.label :fare %><br />
  <%= f.text_field :fare %>
  </div>

<div class="actions">
<%= f.submit "Submit" %>
</div>
<%end%>


<div>

  <%= link_to "Back to train details", train_details_path %>
</div>

app/views/train_details/index.html.erb
<p style="color: green"><%= notice %></p>

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  opacity:10;
}
th, td {
  padding: 5px;
  text-align: left;
}
</style>

<h1>Train details</h1>
<table style="width:100%; background-color:white">   
<thead>   
<tr>  
  <th>Train No</th> 
  <th>Name</th>   
  <th>Frequency</th>   
  <th>Source</th>   
  <th>Destination</th>
  <th>Arrival Time</th> 
  <th>Departure Time</th>
  <th>Distance</th>
  <th>Fare</th> 
  <th>Edit</th>  
</tr>   
</thead>   

<% @train_details.each do |train_detail| %>
    <tr>   
    <td><%= train_detail.train_no %></td> 
    <td><%= train_detail.name %></td> 
    <td><%= train_detail.frequency %></td> 
    <td><%= train_detail.source %></td> 
    <td><%= train_detail.destination %></td> 
    <td><%= train_detail.arrival_time %></td> 
    <td><%= train_detail.departure_time %></td> 
    <td><%= train_detail.distance %></td> 
    <td><%= train_detail.fare %></td> 
    <td><%= link_to "Edit", edit_train_detail_path(train_detail) %></td>
    </tr>
<%end%>
</table>
<%= link_to "New train detail", new_train_detail_path %>
<br>

<%= link_to "sign out", destroy_user_session_path, data: {turbo_method: :delete} %>

app/views/train_details/new.html.erb
<h1>New train detail</h1>

<h2>Sign up</h2>
<%= form_with model: @train_detail do |f| %>



  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    <% @train_detail.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :train_no %><br />
    <%= f.text_field :train_no %>
    <% @train_detail.errors.full_messages_for(:train_no).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
  <%= f.label :departure_time %><br />
  <%= f.datetime_field :departure_time %>
  <% @train_detail.errors.full_messages_for(:departure_time).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>


  <div class="field">
  <%= f.label :arrival_time %><br />
  <%= f.datetime_field :arrival_time %>
  <% @train_detail.errors.full_messages_for(:arrival_time).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div class="field">
  <%= f.label :source %><br />
  <%= f.text_field :source %>
  <% @train_detail.errors.full_messages_for(:source).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

  <div class="field">
  <%= f.label :destination %><br />
  <%= f.text_field :destination %>
  <% @train_detail.errors.full_messages_for(:destination).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

<%= f.select :frequency, options_for_select(TrainDetail.frequencies.map{|k,v| [k.humanize.capitalize,k]}) %>
  
<div class="field">
  <%= f.label :distance %><br />
  <%= f.text_field :distance %>
  <% @train_detail.errors.full_messages_for(:distance).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>


  <div class="field">
  <%= f.label :fare %><br />
  <%= f.text_field :fare %>
  <% @train_detail.errors.full_messages_for(:fare).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

<div class="actions">
<%= f.submit "Submit" %>
</div>
<%end%>

app/views/train_details/search.html.erb
<p style="color: green"><%= notice %></p>

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  opacity:10;
}
th, td {
  padding: 5px;
  text-align: left;
}
</style>

<h1>Train details</h1>
<table style="width:100%; background-color:white">  
  <thead>
    <tr>
      <th>Train Name</th>
      <th>Source</th>
      <th>Destination</th>
      <th>Departure Time</th>
      <th>Arrival Time</th>
      <th>actions</th>

    </tr>
  </thead>
  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.name %></td>
        <td><%= result.source %></td>
        <td><%= result.destination %></td>
        <td><%= result.departure_time %></td>
        <td><%= result.arrival_time %></td>
        <td><%=link_to "Booking" ,new_train_detail_reservation_path(result) %></td>
      </tr>
    <% end %>
  </tbody>
</table>